# Generated by Django 4.2.7 on 2023-11-22 06:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0002_remove_video_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="video_file",
            field=models.FileField(
                upload_to="uploads/video_files",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4", "mpeg4", "mpeg"]
                    )
                ],
            ),
        ),
    ]
